#Atlas-osb. PAS sample

on: [push]
    #  release:
    #types: [created]

name: Prepare CF. Base scenario.

jobs:
  deploy-to-cf:
    name: Prepare CF. Base scenario.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Create CF org, space, broker, service and push app)
        id: prepare
        uses: ./.github/actions/prepare-credhub
        with:
          pcf_url: ${{ secrets.PCF_URL }}
          pcf_user: ${{ secrets.PCF_USER }}
          pcf_password: ${{ secrets.PCF_PASSWORD }}
          atlas_project_id: ${{ secrets.ATLAS_PROJECT_ID }}
          atlas_project_id_bay: ${{ secrets.ATLAS_PROJECT_ID_BAY }}
          atlas_public_key: ${{ secrets.ATLAS_PUBLIC_KEY }}
          atlas_private_key: ${{ secrets.ATLAS_PRIVATE_KEY }}
          credhub_file: ${{ secrets.CREDHUB_FILE }}

      - name: Check application.
        id: check
        env:
          APP_URL: ${{ steps.prepare.outputs.app_url }}
        run: |
          echo "working with "$APP_URL

          # curl -H "Content-Type: application/json" -X PUT -d '{"_class":"org.cloudfoundry.samples.music.domain.Album", "artist": "Tenno", "title": "Journey", "releaseYear": "2019", "genre": "chillhop" }' $APP_URL/albums
          # result=$(curl -X GET $APP_URL/albums -s | awk '/Tenno/{print "true"}')
          # echo $result
          # if [[ -z $result ]]; then
          #   echo "FAILED. Curl check: Text is not found"
          #   exit 1
          # fi

          #for simple-app block (prepare-cf/entrypoint.sh)
          APP_URL=${APP_URL}/service/mongo/test3
          status=$(curl -X PUT -d '{"data":"sometest130"}' ${APP_URL})
          if [[ $status != "success" ]]; then
             echo "Error: check application"
             exit 1
          fi
          result=$(echo $(curl -X GET ${APP_URL}))
          if [ "${result}" = '{"data":"sometest130"}' ]; then
              echo "Application is working"
              echo "Cleaning data.."
              curl -X DELETE ${APP_URL}
          else
              echo "GET ${APP_URL} finished with result: ${result}"
              echo "FAILED. Application doesn't work"
              exit 1
          fi

      - name: Cleanup ENV for current branch
        uses: ./.github/actions/cleanup-cf
        with:
          pcf_url: ${{ secrets.PCF_URL }}
          pcf_user: ${{ secrets.PCF_USER }}
          pcf_password: ${{ secrets.PCF_PASSWORD }}
